### ISSUE TITLE
make rundemo not working

### ISSUE THREAD

**Issue by bbrendon** [django-helpdesk/django-helpdesk#1020]
```
...
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/x/p/venv/lib/python3.9/site-packages/pinax/teams/apps.py", line 2, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/home/x/p/venv/lib/python3.9/site-packages/django/utils/translation/__init__.py)
make: *** [Makefile:84: demo] Error 1
(venv) x@lily:~/p/django-helpdesk$
```

**Comment by gwasser** [comment]
which version of django and helpdesk are you using?

**Comment by gwasser** [comment]
The trace looks like it's actually a problem with pinax, so will have to look into that as a dependency.

**Comment by bbrendon** [comment]
I'm using the helpdesk version from github.

I looked to see what version of django was installed, and there wasn't one. So I ran.
pip3 install django==3.2.13

After installing django, I get a new error.

```
  File "/Users/x/p/django-helpdesk/django-helpdesk/demo/demodesk/config/urls.py", line 30, in <module>
    path('', include('helpdesk.urls', namespace='helpdesk')),
  File "/Users/x/p/django-helpdesk/venv/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/x/p/django-helpdesk/django-helpdesk/helpdesk/urls.py", line 175, in <module>
    url(r'^tickets/(?P<ticket_id>[0-9]+)/dependency/add/$',
NameError: name 'url' is not defined
make: *** [demo] Error 1
```

I think the problem is I assumed all I had to do was check out the code and run `make rundemo`. It seems there are other steps involved.

**Comment by gwasser** [comment]
this is a pretty old script that I don't use very much anymore, so we'll have to either try to fix it or look for an alternative way to quickly run a demo and get users started. as for the url error here, I think this was fixed in #1022 so should be in the next bugfix release (0.4.1).

**Comment by js-on** [comment]
With the current version I can't get it to run as well.
Python 3.10.4 - Manjaro with 5.10 kernel
It crashed with the following dump:
```py
× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [29 lines of output]
    running develop
    /usr/lib/python3.10/site-packages/setuptools/command/easy_install.py:157: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/rtfm/Documents/Docker/Flicket/django-helpdesk/setup.py", line 124, in <module>
        setup(
      File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 155, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 985, in run_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/usr/lib/python3.10/site-packages/setuptools/command/develop.py", line 52, in finalize_options
        easy_install.finalize_options(self)
      File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 276, in finalize_options
        self._fix_install_dir_for_user_site()
      File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 382, in _fix_install_dir_for_user_site
        self.create_home_path()
      File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 1338, in create_home_path
        if path.startswith(home) and not os.path.isdir(path):
    AttributeError: 'int' object has no attribute 'startswith'
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: There was an error checking the latest version of pip.
make: *** [Makefile:82: demo] Error 1
```

**Comment by gwasser** [comment]
Thanks @js-on yeah it looks like it's about time to retire the script. We'll need to figure something else out. In the meantime if you're looking to get a demo, check out [our demo website](http://django-helpdesk-demo.herokuapp.com).

**Comment by DavidVadnais** [comment]
I believe this ticket duplicates #929 so I'm going to close this ticket and link it there.

**Comment by uhurusurfa** [comment]
The script needs a bit of enhancing to avoid being a single run only script.
It should only execute the pieces required that are not already executed and the addition of a demo user needs to accommodate the possibility that the user already exists.
