### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER python manage.py get_email  

### ISSUE THREAD

**Issue by Justin-E-Taylor** [django-helpdesk/django-helpdesk#1114]
This is a new install of django-helpdesk.  I configured a queue to retrieve emails from an MS Exchange server.  I'm getting this SSL error trying to retrieve email.

```
$ python manage.py get_email   
                                                    
Traceback (most recent call last):
  File "C:\django-helpdesk\ibmi_helpdesk\manage.py", line 22, in <module>                                                    
    main()                                                                                                                                                
  File "C:\django-helpdesk\ibmi_helpdesk\manage.py", line 18, in main                                                        
    execute_from_command_line(sys.argv)                                                                                                                   
  File "C:\django-helpdesk\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()                                                                                                                                     
  File "C:\django-helpdesk\venv\lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\django-helpdesk\venv\lib\site-packages\django\core\management\base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\django-helpdesk\venv\lib\site-packages\django\core\management\base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "C:\django-helpdesk\venv\lib\site-packages\helpdesk\management\commands\get_email.py", line 36, in handle
    process_email(quiet=quiet)
  File "C:\django-helpdesk\venv\lib\site-packages\helpdesk\email.py", line 93, in process_email
    process_queue(q, logger=logger)
  File "C:\django-helpdesk\venv\lib\site-packages\helpdesk\email.py", line 389, in process_queue
    server = mail_defaults[email_box_type][encryption]['init'](
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\imaplib.py", line 1324, in __init__
    IMAP4.__init__(self, host, port, timeout)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\imaplib.py", line 202, in __init__
    self.open(host, port, timeout)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\imaplib.py", line 1337, in open
    IMAP4.open(self, host, port, timeout)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\imaplib.py", line 312, in open
    self.sock = self._create_socket(timeout)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\imaplib.py", line 1328, in _create_socket
    return self.ssl_context.wrap_socket(sock,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1041, in _create
    self.do_handshake()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)
```

**Comment by uhurusurfa** [comment]
Are you connecting top the right port in the MS Exchange server that allows using SSL?

**Comment by uhurusurfa** [comment]
I have a feling you are confogured for insecure connection because the default ports are as below:
```
        'imap': {
            'ssl': {
                'port': 993,
                'init': imaplib.IMAP4_SSL,
            },
            'insecure': {
                'port': 143,
                'init': imaplib.IMAP4,
            },
            'sync': imap_sync
        },

```
You must set either of these:

- **email_box_ssl** field on the Queues - this is a per queue setting
- QUEUE_EMAIL_BOX_SSL - set this property to True in the settings.py. This will set the global default to be secure.

**Comment by Justin-E-Taylor** [comment]
I marked SSL when I created the queue.  I'm guessing that's what you mean by email_box_ssl.

I set QUEUE_EMAIL_BOX_SSL to true, and it worked.  Thank you
