### ISSUE TITLE
Docker build lacks of packaging python module

### ISSUE THREAD

**Issue by feroda** [django-helpdesk/django-helpdesk#1224]
**Describe the bug**
The python module "packaging" is not installed as a requirement of the command `pip wheel`

**To Reproduce**

After the repo is cloned do:

`docker build . -t demodesk` 

in order to try django-helpdesk, and I get the following error:

```
1.975   × python setup.py egg_info did not run successfully.
1.975   │ exit code: 1
1.975   ╰─> [10 lines of output]
1.975       Traceback (most recent call last):
1.975         File "<string>", line 2, in <module>
1.975         File "<pip-setuptools-caller>", line 34, in <module>
1.975         File "/tmp/pip-wheel-e42y8et8/django-bootstrap4-form_cb32a7c535854fae8dfe0f97e4924e8b/setup.py", line 2, in <module>
1.975           from bootstrap4form.meta import VERSION
1.975         File "/tmp/pip-wheel-e42y8et8/django-bootstrap4-form_cb32a7c535854fae8dfe0f97e4924e8b/bootstrap4form/__init__.py", line 1, in <module>
1.975           from .meta import VERSION
1.975         File "/tmp/pip-wheel-e42y8et8/django-bootstrap4-form_cb32a7c535854fae8dfe0f97e4924e8b/bootstrap4form/meta.py", line 1, in <module>
1.975           from packaging.version import Version, parse
1.975       ModuleNotFoundError: No module named 'packaging'
1.975       [end of output]
1.975   
1.975   note: This error originates from a subprocess, and is likely not a problem with pip.
1.976 error: metadata-generation-failed
1.976 
1.976 × Encountered error while generating package metadata.
1.976 ╰─> See above for output.
1.976 
1.976 note: This is an issue with the package mentioned above, not pip.
1.976 hint: See above for details.
2.176 
2.176 [notice] A new release of pip is available: 23.2.1 -> 24.3.1
2.176 [notice] To update, run: pip install --upgrade pip
```

**Expected behavior**
The image is build

**Additional context**
I provide a PR

**Comment by uhurusurfa** [comment]
Fixed by #1225
