### ISSUE TITLE
django.contrib.markup is deprecated

### ISSUE THREAD

**Issue by johanovic** [django-helpdesk/django-helpdesk#219]
Following the [docs](http://django-helpdesk.readthedocs.org/en/latest/install.html) one should add `django.contrib.markup` to INSTALLED_APPS.

With `django==1.6.5` That results in the error:

```
 ImportError: No module named markup
```

**Comment by JTchaoren** [comment]
`Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.9.6-py2.7.egg\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django-1.9.6-py2.7.egg\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Python27\lib\site-packages\django-1.9.6-py2.7.egg\django\utils\autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "C:\Python27\lib\site-packages\django-1.9.6-py2.7.egg\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django-1.9.6-py2.7.egg\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python27\lib\site-packages\django-1.9.6-py2.7.egg\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Python27\lib\site-packages\django-1.9.6-py2.7.egg\django\apps\config.py", line 123, in create
    import_module(entry)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named markup`

how to solve  ?

**Comment by JTchaoren** [comment]
> Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.9.6-py2.7.egg\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django-1.9.6-py2.7.egg\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Python27\lib\site-packages\django-1.9.6-py2.7.egg\django\utils\autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "C:\Python27\lib\site-packages\django-1.9.6-py2.7.egg\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django-1.9.6-py2.7.egg\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python27\lib\site-packages\django-1.9.6-py2.7.egg\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Python27\lib\site-packages\django-1.9.6-py2.7.egg\django\apps\config.py", line 123, in create
    import_module(entry)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named markup
 
how to solve?

**Comment by rossp** [comment]
@JTchaoren `django-helpdesk` doesn't use `django.contrib.markup` and hasn't since 2014. Are you looking for a different project perhaps?
