### ISSUE TITLE
Error  while migrating helpdesk

### ISSUE THREAD

**Issue by darshit7** [django-helpdesk/django-helpdesk#386]
Applying helpdesk.0011_admin_related_improvements...Traceback (most recent call last):
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "helpdesk_queue_slug_3b3429c3_like" already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/core/management/**init**.py", line 353, in execute_from_command_line
    utility.execute()
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/core/management/**init**.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/core/management/base.py", line 348, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/core/management/base.py", line 399, in execute
    output = self.handle(_args, *_options)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/db/migrations/operations/fields.py", line 201, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/db/backends/base/schema.py", line 482, in alter_field
    old_db_params, new_db_params, strict)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/db/backends/postgresql/schema.py", line 116, in _alter_field
    self.execute(like_index_statement)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/db/backends/base/schema.py", line 110, in execute
    cursor.execute(sql, params)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "helpdesk_queue_slug_3b3429c3_like" already exists

**Comment by gwasser** [comment]
@darshit7 We've made some improvements to our migration files and its been quite some time, so I'm going to go ahead and close this out for now, but please feel free to file a new ticket if you're still having trouble!
