### ISSUE TITLE
manage.py migrate helpdesk not working 

### ISSUE THREAD

**Issue by tOlorun** [django-helpdesk/django-helpdesk#489]
Please assist with the below error
i have been @ this for 2 days now very :-1:  and very very :(

Many thanks

`$ python manage.py migrate helpdesk
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 89, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 170, in build_graph
    self.load_disk()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 105, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/helpdesk/migrations/0005_auto__add_field_customfield_empty_selection_list.py", line 3, in <module>
    from south.db import db
  File "/usr/local/lib/python2.7/dist-packages/south/db/__init__.py", line 84, in <module>
    db = dbs[DEFAULT_DB_ALIAS]
KeyError: 'default'
`

**Comment by tOlorun** [comment]
And when i add the below to the settings file 

`SOUTH_DATABASE_ADAPTERS = {
    # 'default': "django.db.backends.postgresql"
    'default': "django.db.backends.postgresql_psycopg2"
}`

i get the following error
`$ python manage.py migrate helpdesk
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 89, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 170, in build_graph
    self.load_disk()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 105, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/helpdesk/migrations/0005_auto__add_field_customfield_empty_selection_list.py", line 3, in <module>
    from south.db import db
  File "/usr/local/lib/python2.7/dist-packages/south/db/__init__.py", line 70, in <module>
    dbs[alias] = module.DatabaseOperations(alias)
AttributeError: 'module' object has no attribute 'DatabaseOperations'
`


many thanks in advance

**Comment by gwasser** [comment]
Hi @tOlorun sorry to hear about your trouble.

It looks like you're trying to use south migrations? I don't have much experience with them myself. Which version of django-helpdesk are you using? Are you running this on a pre-existing Django project or a new one from scratch?

**Comment by andresf01** [comment]
Hi @tOlorun I had the same trouble. 
I deleted my database and create again, then I applied the migrations and all ok.

**Comment by gwasser** [comment]
Thanks for the follow-up @andresf01 . I suppose there's some issue with migrating from old databases that used south? Were you able to solve the issue @tOlorun ?

**Comment by gwasser** [comment]
Hey @tOlorun I'm going to go ahead and close this ticket since I haven't heard from you and assume you got it working, but if you have any more trouble please feel free to file a new one!
