### ISSUE TITLE
Get_email 'Command' object has no attribute 'option_list'

### ISSUE THREAD

**Issue by MBuffenoir** [django-helpdesk/django-helpdesk#509]
Using django 1.10.7.

After setting up my queue in the admin, I try to run the get_email command and get the following error:

```
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 41, in load_command_class
    return module.Command()
  File "/usr/local/lib/python3.5/site-packages/helpdesk/management/commands/get_email.py", line 55, in __init__
    self.option_list += (
AttributeError: 'Command' object has no attribute 'option_list'
```

I have no idea how to fix this yet.

**Comment by gwasser** [comment]
Hi @MBuffenoir that error comes from the way the script used to process command line options. It basically uses a library that only works in Python 2. You can either run the current release of helpdesk (0.1.18 I think) in Python 2, or if you'd like to use Python 3 and help us test our next release, the master branch on github here has the beta of version 0.2 which supports Python 3 much better.

**Comment by MBuffenoir** [comment]
Thanks for your answer @gwasser.  I did not realise python 3 was not supported. OK I will test the beta of the new version.

**Comment by gwasser** [comment]
If you try it let us know! We've improved Python 3 support and added expanded test coverage but we're still trying to add more test cases to make sure all bases are covered. If you spot any problems, please file a ticket or a pull request if you'd like to add some tests yourself!
