### ISSUE TITLE
imaplib.error: command SEARCH illegal in state AUTH, only allowed in states SELECTED

### ISSUE THREAD

**Issue by ddwaraka** [django-helpdesk/django-helpdesk#536]
I'm trying to setup a cron job for django-helpdesk to create tickets from my inbox. I've configured a cron job and then I tried to do this:
`python manage.py get_email`

It gives me this error: 
`imaplib.error: command SEARCH illegal in state AUTH, only allowed in states SELECTED`

Here's the full error log:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/commercial/.virtualenvs/projects/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/commercial/.virtualenvs/projects/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/commercial/.virtualenvs/projects/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/commercial/.virtualenvs/projects/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/commercial/.virtualenvs/projects/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 73, in handle
    process_email(quiet=quiet)
  File "/home/commercial/.virtualenvs/projects/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 106, in process_email
    process_queue(q, logger=logger)
  File "/home/commercial/.virtualenvs/projects/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 198, in process_queue
    status, data = server.search(None, 'NOT', 'DELETED')
  File "/usr/lib64/python2.7/imaplib.py", line 639, in search
    typ, dat = self._simple_command(name, *criteria)
  File "/usr/lib64/python2.7/imaplib.py", line 1082, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib64/python2.7/imaplib.py", line 837, in _command
    ', '.join(Commands[name])))
imaplib.error: command SEARCH illegal in state AUTH, only allowed in states SELECTED
```

Are there steps I'm missing somewhere? I'm following what is mentioned here: 
https://django-helpdesk.readthedocs.io/en/latest/configuration.html
```

**Comment by gwasser** [comment]
You may have stumbled on a bug here. I think the IMAP code is a little less well tested than other areas.

It looks like it's failing to select your IMAP folder before performing a search. Since the line immediately before the one that crashes is a select() statement, I'm thinking the IMAP folder you're trying to reach might not exist, and we're not properly checking that and notifying you before it crashes hard, so at a minimum we should provide a better error message here.

Please double-check that the IMAP folder you requested exists on the server and that you have added the folder name to your Queue configuration (if it is blank, it tries the default folder of 'INBOX' which maybe your email server doesn't have?).

**Comment by ddwaraka** [comment]
Yes, you're right, the folder name had a typo. That's why it wasn't seeing it. I fixed the name and that fixed the issue. Thank you so much!

**Comment by gwasser** [comment]
Awesome! Glad it was an easy fix. I still think we need a better error message here so I'll keep the ticket open for now to remind myself. Let us know if you have any other problems.

**Comment by gwasser** [comment]
Added a logger error message suggesting user check if IMAP folder is spelled correctly and exists. Committed to `master` for the 0.2.0 release. Hopefully this will help anyone else encountering the error!
