### ISSUE TITLE
TypeError for __init__() when migrating

### ISSUE THREAD

**Issue by KeshavZbhide** [django-helpdesk/django-helpdesk#548]
File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/kbhide/django/django/core/management/__init__.py", line 366, in execute_from_command_line
    utility.execute()
  File "/home/kbhide/django/django/core/management/__init__.py", line 342, in execute
    django.setup()
  File "/home/kbhide/django/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/kbhide/django/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/kbhide/django/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/kbhide/.local/lib/python3.5/site-packages/helpdesk/models.py", line 26, in <module>
    class Queue(models.Model):
  File "/home/kbhide/.local/lib/python3.5/site-packages/helpdesk/models.py", line 227, in Queue
    verbose_name=_('Default owner'),
TypeError: __init__() missing 1 required positional argument: 'on_delete'

While running  `./manage.py migrate helpdesk`. I get the above error I followed all the steps on 
http://django-helpdesk.readthedocs.io/en/latest/install.html#adding-to-your-django-project 

Can some one help me with this.

**Comment by gwasser** [comment]
Hello! Looks like you're using our current release (0.1.18) on Python 3, which isn't fully supported. The `master` branch supports Python 3. I intend on releasing version 0.2.0 which supports Python 3 in the next few days after some last minute tests, either check out `master` or give 0.2.0 a shot when it comes out.

**Comment by KeshavZbhide** [comment]
Hi Garret.

I checked-out the master branch with  `git clone -b master https://github.com/django-helpdesk/django-helpdesk.git`
later I installed it with `python3 setup.py install`

But still I get the same error:


Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/kbhide/django/django/core/management/__init__.py", line 366, in execute_from_command_line
    utility.execute()
  File "/home/kbhide/django/django/core/management/__init__.py", line 342, in execute
    django.setup()
  File "/home/kbhide/django/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/kbhide/django/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/kbhide/django/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/django_helpdesk-0.2.0-py3.5.egg/helpdesk/models.py", line 22, in <module>
    class Queue(models.Model):
  File "/usr/local/lib/python3.5/dist-packages/django_helpdesk-0.2.0-py3.5.egg/helpdesk/models.py", line 261, in Queue
    verbose_name=_('Default owner'),
TypeError: __init__() missing 1 required positional argument: 'on_delete'

**Comment by gwasser** [comment]
Sorry! I didn't look too closely, I saw you were using Py3 and hoped that would fix it.

What version of Django are you using? Are you using a beta or `master` for django? `on_delete` shouldn't be required until Django 2.0 according to [this page](https://docs.djangoproject.com/en/1.11/ref/models/fields/#django.db.models.ForeignKey.on_delete) and the demo project seems to work well for me under Py3 + Django 1.11, so I'd have to dig in more if that isn't the case.

**Comment by KeshavZbhide** [comment]
my django version is 2.0.dev20170827005745

**Comment by gwasser** [comment]
Hmm well somehow you ended up with the development branch of django 2.0 (it hasn't been released yet). Django 2.0 makes a bunch of changes and I haven't checked for them yet. We only support Django 1.11. I think you can do something like `pip install django=1.11` to install a particular version. Please give that a try and let me know if it fixes the problem. I'll have to update our documentation to say we don't support Django 2.0 in this upcoming release. Thanks!

**Comment by KeshavZbhide** [comment]
Thanks, it works now.

**Comment by gwasser** [comment]
Awesome! I updated our documentation to say that only Django 1.11 is supported in the next release (0.2.0). Let me know if you have other questions but I will close this for now.
