### ISSUE TITLE
SSL - read operation timed out

### ISSUE THREAD

**Issue by mrkiwi-nz** [django-helpdesk/django-helpdesk#568]
For some months now I have been getting errors sometimes when the cron job grabs helpdesk messages from the IMAP queue.
It doesn't cause too many problems - the emails will usually be successfully grabbed 5 minutes later, and will *always* run fine when run from an interactive shell like this:
`>python manage.py get_email`
I suspect it relates to a timeout issue.

I wonder if get_email.py, line 207, should be wrapped in a try / catch? 
Or ... maybe introduce a timeout value in helpdesk's settings which defaults to the current value?

Does anyone else get these? 

If i ran the cron job like this:
`python manage.py get_email --quiet >/dev/null`
or similar I would never have noticed this happening.

`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/e-smith/files/ibays/django/django_app/m10_repo/m10virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/e-smith/files/ibays/django/django_app/m10_repo/m10virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/e-smith/files/ibays/django/django_app/m10_repo/m10virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/e-smith/files/ibays/django/django_app/m10_repo/m10virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/e-smith/files/ibays/django/django_app/m10_repo/m10virtualenv/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 73, in handle
    process_email(quiet=quiet)
  File "/home/e-smith/files/ibays/django/django_app/m10_repo/m10virtualenv/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 106, in process_email
    process_queue(q, logger=logger)
  File "/home/e-smith/files/ibays/django/django_app/m10_repo/m10virtualenv/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 207, in process_queue
    status, data = server.fetch(num, '(RFC822)')
  File "/usr/local/lib/python2.7/imaplib.py", line 456, in fetch
    typ, dat = self._simple_command(name, message_set, message_parts)
  File "/usr/local/lib/python2.7/imaplib.py", line 1088, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/local/lib/python2.7/imaplib.py", line 910, in _command_complete
    typ, data = self._get_tagged_response(tag)
  File "/usr/local/lib/python2.7/imaplib.py", line 1017, in _get_tagged_response
    self._get_response()
  File "/usr/local/lib/python2.7/imaplib.py", line 929, in _get_response
    resp = self._get_line()
  File "/usr/local/lib/python2.7/imaplib.py", line 1027, in _get_line
    line = self.readline()
  File "/usr/local/lib/python2.7/imaplib.py", line 1189, in readline
    return self.file.readline()
  File "/usr/local/lib/python2.7/socket.py", line 451, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/ssl.py", line 734, in recv
    return self.read(buflen)
  File "/usr/local/lib/python2.7/ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
ssl.SSLError: ('The read operation timed out',)`

**Comment by mrkiwi-nz** [comment]
Also we get this error (less frequently, but i'm sure it's related)

`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/e-smith/files/ibays/django/django_app/m10_repo/m10virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/e-smith/files/ibays/django/django_app/m10_repo/m10virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/e-smith/files/ibays/django/django_app/m10_repo/m10virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/e-smith/files/ibays/django/django_app/m10_repo/m10virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/e-smith/files/ibays/django/django_app/m10_repo/m10virtualenv/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 73, in handle
    process_email(quiet=quiet)
  File "/home/e-smith/files/ibays/django/django_app/m10_repo/m10virtualenv/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 106, in process_email
    process_queue(q, logger=logger)
  File "/home/e-smith/files/ibays/django/django_app/m10_repo/m10virtualenv/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 182, in process_queue
    int(q.email_box_port))
  File "/usr/local/lib/python2.7/imaplib.py", line 1166, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/local/lib/python2.7/imaplib.py", line 173, in __init__
    self.open(host, port)
  File "/usr/local/lib/python2.7/imaplib.py", line 1178, in open
    self.sslobj = ssl.wrap_socket(self.sock, self.keyfile, self.certfile)
  File "/usr/local/lib/python2.7/ssl.py", line 911, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/usr/local/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: ('_ssl.c:574: The handshake operation timed out',)`

**Comment by gwasser** [comment]
I added a commit to `master` that wrapped the IMAP login attempt in a try-except block. I simply log that it failed (logging a timeout if we see the `ssl.SSLError` in your debug stuff above) and exit the script, so it closes instead of crashes. I figured this is enough for now since `cron` will simply run it again at whatever your next interval is, and the error is logged. If you have some time, please check out this update from `master`. I'll wrap this into the next bug fix release very soon. Thanks!

**Comment by gwasser** [comment]
I added this to the 0.2.3 release, so I'm going to go ahead and close it for now. But please re-open or file a new ticket if you spot any problems or have further suggestions. Thanks!
