### ISSUE TITLE
Cannot easily send ticket updates with quotes of django tempaltes

### ISSUE THREAD

**Issue by timthelion** [django-helpdesk/django-helpdesk#723]
If I include a quote from a django template in a update to a ticket, django-helpdesk actually tries to parse the template syntax resulting in erorrs. These errors are not properly handled.

````
2019-03-04T13:18:55.104111+00:00 app[web.1]: 
2019-03-04T13:18:55.104113+00:00 app[web.1]: Traceback (most recent call last):
2019-03-04T13:18:55.104114+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
2019-03-04T13:18:55.104116+00:00 app[web.1]:     response = get_response(request)
2019-03-04T13:18:55.104117+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
2019-03-04T13:18:55.104119+00:00 app[web.1]:     response = response or self.get_response(request)
2019-03-04T13:18:55.104121+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/hooks/framework_django.py", line 1203, in _wrapper
2019-03-04T13:18:55.104122+00:00 app[web.1]:     return wrapped(*args, **kwargs)
2019-03-04T13:18:55.104124+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
2019-03-04T13:18:55.104125+00:00 app[web.1]:     response = response_for_exception(request, exc)
2019-03-04T13:18:55.104127+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 95, in response_for_exception
2019-03-04T13:18:55.104128+00:00 app[web.1]:     exc_info=sys.exc_info(),
2019-03-04T13:18:55.104130+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/log.py", line 228, in log_response
2019-03-04T13:18:55.104132+00:00 app[web.1]:     exc_info=exc_info,
2019-03-04T13:18:55.104133+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/logging/__init__.py", line 1329, in error
2019-03-04T13:18:55.104135+00:00 app[web.1]:     Log 'msg % args' with severity 'ERROR'.
2019-03-04T13:18:55.104136+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/logging/__init__.py", line 1337, in error
2019-03-04T13:18:55.104138+00:00 app[web.1]:     self._log(ERROR, msg, args, **kwargs)
2019-03-04T13:18:55.104140+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/logging/__init__.py", line 1444, in _log
2019-03-04T13:18:55.104141+00:00 app[web.1]:     self.handle(record)
2019-03-04T13:18:55.104143+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/logging/__init__.py", line 1454, in handle
2019-03-04T13:18:55.104144+00:00 app[web.1]:     self.callHandlers(record)
2019-03-04T13:18:55.104150+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
2019-03-04T13:18:55.104152+00:00 app[web.1]:     hdlr.handle(record)
2019-03-04T13:18:55.104153+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/logging/__init__.py", line 865, in handle
2019-03-04T13:18:55.104155+00:00 app[web.1]:     self.emit(record)
2019-03-04T13:18:55.104156+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/log.py", line 122, in emit
2019-03-04T13:18:55.104158+00:00 app[web.1]:     self.send_mail(subject, message, fail_silently=True, html_message=html_message)
2019-03-04T13:18:55.104159+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/log.py", line 125, in send_mail
2019-03-04T13:18:55.104161+00:00 app[web.1]:     mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
2019-03-04T13:18:55.104162+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/api/function_trace.py", line 139, in literal_wrapper
2019-03-04T13:18:55.104164+00:00 app[web.1]:     return wrapped(*args, **kwargs)
2019-03-04T13:18:55.104165+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/mail/__init__.py", line 101, in mail_admins
2019-03-04T13:18:55.104167+00:00 app[web.1]:     mail.send(fail_silently=fail_silently)
2019-03-04T13:18:55.104169+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/api/function_trace.py", line 139, in literal_wrapper
2019-03-04T13:18:55.104170+00:00 app[web.1]:     return wrapped(*args, **kwargs)
2019-03-04T13:18:55.104172+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/mail/message.py", line 291, in send
2019-03-04T13:18:55.104173+00:00 app[web.1]:     return self.get_connection(fail_silently).send_messages([self])
2019-03-04T13:18:55.104175+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/post_office/backends.py", line 48, in send_messages
2019-03-04T13:18:55.104176+00:00 app[web.1]:     headers=headers)
2019-03-04T13:18:55.104177+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/post_office/mail.py", line 65, in create
2019-03-04T13:18:55.104179+00:00 app[web.1]:     message = Template(message).render(_context)
2019-03-04T13:18:55.104181+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
2019-03-04T13:18:55.104182+00:00 app[web.1]:     self.nodelist = self.compile_nodelist()
2019-03-04T13:18:55.104184+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
2019-03-04T13:18:55.104185+00:00 app[web.1]:     return parser.parse()
2019-03-04T13:18:55.104187+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
2019-03-04T13:18:55.104188+00:00 app[web.1]:     raise self.error(token, e)
2019-03-04T13:18:55.104190+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
2019-03-04T13:18:55.104191+00:00 app[web.1]:     compiled_result = compile_func(self, token)
2019-03-04T13:18:55.104193+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 315, in do_include
2019-03-04T13:18:55.104195+00:00 app[web.1]:     bits[1] = construct_relative_path(parser.origin.template_name, bits[1])
2019-03-04T13:18:55.104196+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 232, in construct_relative_path
2019-03-04T13:18:55.104198+00:00 app[web.1]:     posixpath.dirname(current_template_name.lstrip('/')),
2019-03-04T13:18:55.104200+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'lstrip'
2019-03-04T13:18:55.104201+00:00 app[web.1]: 
2019-03-04T13:18:55.104203+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2019-03-04T13:18:55.104204+00:00 app[web.1]: 
2019-03-04T13:18:55.104206+00:00 app[web.1]: Traceback (most recent call last):
2019-03-04T13:18:55.104207+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
2019-03-04T13:18:55.104209+00:00 app[web.1]:     response = get_response(request)
2019-03-04T13:18:55.104210+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
2019-03-04T13:18:55.104211+00:00 app[web.1]:     response = response or self.get_response(request)
2019-03-04T13:18:55.104213+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/hooks/framework_django.py", line 1203, in _wrapper
2019-03-04T13:18:55.104215+00:00 app[web.1]:     return wrapped(*args, **kwargs)
2019-03-04T13:18:55.104216+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
2019-03-04T13:18:55.104218+00:00 app[web.1]:     response = response_for_exception(request, exc)
2019-03-04T13:18:55.104223+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 95, in response_for_exception
2019-03-04T13:18:55.104225+00:00 app[web.1]:     exc_info=sys.exc_info(),
2019-03-04T13:18:55.104227+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/log.py", line 228, in log_response
2019-03-04T13:18:55.104228+00:00 app[web.1]:     exc_info=exc_info,
2019-03-04T13:18:55.104230+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/logging/__init__.py", line 1329, in error
2019-03-04T13:18:55.104231+00:00 app[web.1]:     Log 'msg % args' with severity 'ERROR'.
2019-03-04T13:18:55.104233+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/logging/__init__.py", line 1337, in error
2019-03-04T13:18:55.104234+00:00 app[web.1]:     self._log(ERROR, msg, args, **kwargs)
2019-03-04T13:18:55.104236+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/logging/__init__.py", line 1444, in _log
2019-03-04T13:18:55.104237+00:00 app[web.1]:     self.handle(record)
2019-03-04T13:18:55.104239+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/logging/__init__.py", line 1454, in handle
2019-03-04T13:18:55.104241+00:00 app[web.1]:     self.callHandlers(record)
2019-03-04T13:18:55.104242+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
2019-03-04T13:18:55.104248+00:00 app[web.1]:     hdlr.handle(record)
2019-03-04T13:18:55.104250+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/logging/__init__.py", line 865, in handle
2019-03-04T13:18:55.104251+00:00 app[web.1]:     self.emit(record)
2019-03-04T13:18:55.104253+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/log.py", line 122, in emit
2019-03-04T13:18:55.104255+00:00 app[web.1]:     self.send_mail(subject, message, fail_silently=True, html_message=html_message)
2019-03-04T13:18:55.104256+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/log.py", line 125, in send_mail
2019-03-04T13:18:55.104258+00:00 app[web.1]:     mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
2019-03-04T13:18:55.104259+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/api/function_trace.py", line 139, in literal_wrapper
2019-03-04T13:18:55.104261+00:00 app[web.1]:     return wrapped(*args, **kwargs)
2019-03-04T13:18:55.104262+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/mail/__init__.py", line 101, in mail_admins
2019-03-04T13:18:55.104263+00:00 app[web.1]:     mail.send(fail_silently=fail_silently)
2019-03-04T13:18:55.104265+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/api/function_trace.py", line 139, in literal_wrapper
2019-03-04T13:18:55.104267+00:00 app[web.1]:     return wrapped(*args, **kwargs)
2019-03-04T13:18:55.104268+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/mail/message.py", line 291, in send
2019-03-04T13:18:55.104270+00:00 app[web.1]:     return self.get_connection(fail_silently).send_messages([self])
2019-03-04T13:18:55.104271+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/post_office/backends.py", line 48, in send_messages
2019-03-04T13:18:55.104272+00:00 app[web.1]:     headers=headers)
2019-03-04T13:18:55.104274+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/post_office/mail.py", line 65, in create
2019-03-04T13:18:55.104275+00:00 app[web.1]:     message = Template(message).render(_context)
2019-03-04T13:18:55.104277+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
2019-03-04T13:18:55.104278+00:00 app[web.1]:     self.nodelist = self.compile_nodelist()
2019-03-04T13:18:55.104280+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
2019-03-04T13:18:55.104281+00:00 app[web.1]:     return parser.parse()
2019-03-04T13:18:55.104283+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
2019-03-04T13:18:55.104284+00:00 app[web.1]:     raise self.error(token, e)
2019-03-04T13:18:55.104286+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
2019-03-04T13:18:55.104287+00:00 app[web.1]:     compiled_result = compile_func(self, token)
2019-03-04T13:18:55.104289+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 315, in do_include
2019-03-04T13:18:55.104290+00:00 app[web.1]:     bits[1] = construct_relative_path(parser.origin.template_name, bits[1])
2019-03-04T13:18:55.104292+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 232, in construct_relative_path
2019-03-04T13:18:55.104293+00:00 app[web.1]:     posixpath.dirname(current_template_name.lstrip('/')),
2019-03-04T13:18:55.104295+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'lstrip'
2019-03-04T13:18:55.104296+00:00 app[web.1]: 
2019-03-04T13:18:55.104298+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2019-03-04T13:18:55.104299+00:00 app[web.1]: 
2019-03-04T13:18:55.104301+00:00 app[web.1]: Traceback (most recent call last):
2019-03-04T13:18:55.104302+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
2019-03-04T13:18:55.105292+00:00 app[web.1]:     return wrapped(*args, **kwargs)
2019-03-04T13:18:55.105306+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/mail/message.py", line 291, in send
2019-03-04T13:18:55.105308+00:00 app[web.1]:     return self.get_connection(fail_silently).send_messages([self])
2019-03-04T13:18:55.105310+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/post_office/backends.py", line 48, in send_messages
2019-03-04T13:18:55.105311+00:00 app[web.1]:     headers=headers)
2019-03-04T13:18:55.105313+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/post_office/mail.py", line 65, in create
2019-03-04T13:18:55.105315+00:00 app[web.1]:     message = Template(message).render(_context)
2019-03-04T13:18:55.105316+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
2019-03-04T13:18:55.105317+00:00 app[web.1]:     self.nodelist = self.compile_nodelist()
2019-03-04T13:18:55.105319+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
2019-03-04T13:18:55.105321+00:00 app[web.1]:     return parser.parse()
2019-03-04T13:18:55.105322+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
2019-03-04T13:18:55.105324+00:00 app[web.1]:     raise self.error(token, e)
2019-03-04T13:18:55.105325+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
2019-03-04T13:18:55.105326+00:00 app[web.1]:     compiled_result = compile_func(self, token)
2019-03-04T13:18:55.105328+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 315, in do_include
2019-03-04T13:18:55.105329+00:00 app[web.1]:     bits[1] = construct_relative_path(parser.origin.template_name, bits[1])
2019-03-04T13:18:55.105331+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 232, in construct_relative_path
2019-03-04T13:18:55.105332+00:00 app[web.1]:     posixpath.dirname(current_template_name.lstrip('/')),
2019-03-04T13:18:55.105387+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'lstrip'
````

**Comment by timthelion** [comment]
Try putting `{% include "./non-existant.html"  %}` in your follow up to test.

**Comment by gwasser** [comment]
I tried adding that to a follow-up on the online demo and didn't encounter any error messages. Can you give more detail?

**Comment by timthelion** [comment]
I believe that the reason this is not reproducible in the demo desk is that the problem occurs in the function send_templated_mail https://github.com/django-helpdesk/django-helpdesk/blob/cfd838b7f450de54a31594b7bef02d7c9cd70842/helpdesk/lib.py#L38

**Comment by gwasser** [comment]
Oh ok, I saw "heroku" in your log there and thought you were using demo desk.

**Comment by uhurusurfa** [comment]
If this is still an issue please reopen and provide more detail on exactly what you are trying to do.
