### ISSUE TITLE
heroku.com failed to compile Python app.

### ISSUE THREAD

**Issue by tqangxl** [django-helpdesk/django-helpdesk#737]
-----> Python app detected
-----> Installing python-3.6.8
-----> Installing pip
-----> Installing SQLite3
-----> Installing requirements with pip
       Collecting Django<3,>=1.11 (from -r /tmp/build_4bc53176568030230c2631dd9f60add4/requirements.txt (line 1))
         Downloading https://files.pythonhosted.org/packages/c7/87/fbd666c4f87591ae25b7bb374298e8629816e87193c4099d3608ef11fab9/Django-2.1.7-py3-none-any.whl (7.3MB)
       Collecting django-bootstrap-form<4,>=3.3 (from -r /tmp/build_4bc53176568030230c2631dd9f60add4/requirements.txt (line 2))
         Downloading https://files.pythonhosted.org/packages/c7/3d/4ec51e3816d3bd5959058e210598e819fb86d492d16a19d195a025a64758/django-bootstrap-form-3.4.tar.gz
       Collecting email-reply-parser (from -r /tmp/build_4bc53176568030230c2631dd9f60add4/requirements.txt (line 3))
         Downloading https://files.pythonhosted.org/packages/f1/6d/d09ed9032fab34c28fb95fa654772f8a8f446884541730c79559597b3f2f/email_reply_parser-0.5.9.tar.gz
       Collecting django-markdown-deux (from -r /tmp/build_4bc53176568030230c2631dd9f60add4/requirements.txt (line 4))
         Downloading https://files.pythonhosted.org/packages/80/a5/d61ee6fc26cbb0d737986ed23e13309c88f2ae7f1fcdf2460a525323a3ed/django-markdown-deux-1.0.5.zip
       Collecting beautifulsoup4 (from -r /tmp/build_4bc53176568030230c2631dd9f60add4/requirements.txt (line 5))
         Downloading https://files.pythonhosted.org/packages/1d/5d/3260694a59df0ec52f8b4883f5d23b130bc237602a1411fa670eae12351e/beautifulsoup4-4.7.1-py3-none-any.whl (94kB)
       Collecting lxml (from -r /tmp/build_4bc53176568030230c2631dd9f60add4/requirements.txt (line 6))
         Downloading https://files.pythonhosted.org/packages/79/ae/35f5dbbac8efec8b8d1300858f1ce0b453ea2ff644abe6b5c5c358013dfa/lxml-4.3.2-cp36-cp36m-manylinux1_x86_64.whl (5.7MB)
       Collecting simplejson (from -r /tmp/build_4bc53176568030230c2631dd9f60add4/requirements.txt (line 7))
         Downloading https://files.pythonhosted.org/packages/e3/24/c35fb1c1c315fc0fffe61ea00d3f88e85469004713dab488dee4f35b0aff/simplejson-3.16.0.tar.gz (81kB)
       Collecting pytz (from -r /tmp/build_4bc53176568030230c2631dd9f60add4/requirements.txt (line 8))
         Downloading https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl (510kB)
       Collecting six (from -r /tmp/build_4bc53176568030230c2631dd9f60add4/requirements.txt (line 9))
         Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
       Collecting markdown2 (from django-markdown-deux->-r /tmp/build_4bc53176568030230c2631dd9f60add4/requirements.txt (line 4))
         Downloading https://files.pythonhosted.org/packages/e4/0c/b5375c1c70adbafd0ded0459fa175468559ee5360219070d2f7fb60b2287/markdown2-2.3.7-py2.py3-none-any.whl
       Collecting soupsieve>=1.2 (from beautifulsoup4->-r /tmp/build_4bc53176568030230c2631dd9f60add4/requirements.txt (line 5))
         Downloading https://files.pythonhosted.org/packages/77/78/bca00cc9fa70bba1226ee70a42bf375c4e048fe69066a0d9b5e69bc2a79a/soupsieve-1.8-py2.py3-none-any.whl (88kB)
       Installing collected packages: pytz, Django, django-bootstrap-form, email-reply-parser, markdown2, django-markdown-deux, soupsieve, beautifulsoup4, lxml, simplejson, six
         Running setup.py install for django-bootstrap-form: started
           Running setup.py install for django-bootstrap-form: finished with status 'done'
         Running setup.py install for email-reply-parser: started
           Running setup.py install for email-reply-parser: finished with status 'done'
         Running setup.py install for django-markdown-deux: started
           Running setup.py install for django-markdown-deux: finished with status 'done'
         Running setup.py install for simplejson: started
           Running setup.py install for simplejson: finished with status 'done'
       Successfully installed Django-2.1.7 beautifulsoup4-4.7.1 django-bootstrap-form-3.4 django-markdown-deux-1.0.5 email-reply-parser-0.5.9 lxml-4.3.2 markdown2-2.3.7 pytz-2018.9 simplejson-3.16.0 six-1.12.0 soupsieve-1.8
-----> $ python demo/demodesk/manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 204, in fetch_command
           app_name = commands[subcommand]
       KeyError: 'collectstatic'
       During handling of the above exception, another exception occurred:
       Traceback (most recent call last):
         File "demo/demodesk/manage.py", line 25, in <module>
           main()
         File "demo/demodesk/manage.py", line 22, in main
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 211, in fetch_command
           settings.INSTALLED_APPS
         File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
           self._setup(name)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 44, in _setup
           self._wrapped = Settings(settings_module)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 107, in __init__
           mod = importlib.import_module(self.SETTINGS_MODULE)
         File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
           return _bootstrap._gcd_import(name[level:], package, level)
         File "<frozen importlib._bootstrap>", line 994, in _gcd_import
         File "<frozen importlib._bootstrap>", line 971, in _find_and_load
         File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
         File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
         File "<frozen importlib._bootstrap>", line 994, in _gcd_import
         File "<frozen importlib._bootstrap>", line 971, in _find_and_load
         File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
         File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
         File "<frozen importlib._bootstrap>", line 994, in _gcd_import
         File "<frozen importlib._bootstrap>", line 971, in _find_and_load
         File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
       ModuleNotFoundError: No module named 'demodesk'
 !     Error while running '$ python demo/demodesk/manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by gwasser** [comment]
Are you trying to install the `demodesk` files? Make sure those files are in a demodesk folder within your root if so.
