### ISSUE TITLE
Gmail delivery status notification emails cannot be fetched.

### ISSUE THREAD

**Issue by csinsota** [django-helpdesk/django-helpdesk#771]
Hello,
I'm using gmail during development and noticed that Gmail delivery status notification emails cannot be fetched via the get_email management command. I tested this issue in master and develop branch.  Please see error messages below. 
Problematic email: 
[Delivery Status Notification (Delay).txt](https://github.com/django-helpdesk/django-helpdesk/files/3513506/Delivery.Status.Notification.Delay.txt)

**To Reproduce**
1. Use gmail to send mail to non existent address like 'none@example.com'
2. Wait for gmail status notification email
3. Try to fetch these emails via get_email management command (via IMAP)

**Error message in master branch (0.2.16) [that would normally be suppressed](https://github.com/django-helpdesk/django-helpdesk/blob/b41f95fd7e715b756cf456315bf9ad143da8fe97/helpdesk/management/commands/get_email.py#L244), but I re-raised it:**

> Traceback (most recent call last):
  File "/home/cs/test_helpdesk/.venv/lib/python3.6/site-packages/helpdesk/management/commands/get_email.py", line 241, in process_queue
    ticket = ticket_from_message(message=full_message, queue=q, logger=logger)
  File "/home/cs/test_helpdesk/.venv/lib/python3.6/site-packages/helpdesk/management/commands/get_email.py", line 402, in ticket_from_message
    mail = BeautifulSoup(part.get_payload(), "lxml")
  File "/home/cs/test_helpdesk/.venv/lib/python3.6/site-packages/bs4/__init__.py", line 300, in __init__
    markup, from_encoding, exclude_encodings=exclude_encodings)):
  File "/home/cs/test_helpdesk/.venv/lib/python3.6/site-packages/bs4/builder/_lxml.py", line 150, in prepare_markup
    for encoding in detector.encodings:
  File "/home/cs/test_helpdesk/.venv/lib/python3.6/site-packages/bs4/dammit.py", line 265, in encodings
    self.markup, self.is_html)
  File "/home/cs/test_helpdesk/.venv/lib/python3.6/site-packages/bs4/dammit.py", line 323, in find_declared_encoding
    declared_encoding_match = xml_encoding_re.search(markup, endpos=xml_endpos)
TypeError: expected string or bytes-like object

**Error message in develop branch:**
> Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/cs/test_helpdesk/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/cs/test_helpdesk/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/cs/test_helpdesk/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/cs/test_helpdesk/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/cs/test_helpdesk/.venv/lib/python3.6/site-packages/helpdesk/management/commands/get_email.py", line 37, in handle
    process_email(quiet=quiet)
  File "/home/cs/test_helpdesk/.venv/lib/python3.6/site-packages/helpdesk/email.py", line 86, in process_email
    process_queue(q, logger=logger)
  File "/home/cs/test_helpdesk/.venv/lib/python3.6/site-packages/helpdesk/email.py", line 231, in process_queue
    mail_defaults[email_box_type]['sync'](q, logger, server)
  File "/home/cs/test_helpdesk/.venv/lib/python3.6/site-packages/helpdesk/email.py", line 156, in imap_sync
    ticket = object_from_message(message=full_message, queue=q, logger=logger)
  File "/home/cs/test_helpdesk/.venv/lib/python3.6/site-packages/helpdesk/email.py", line 523, in object_from_message
    mail = BeautifulSoup(str(message), "html.parser")
  File "/usr/lib/python3.6/email/message.py", line 135, in __str__
    return self.as_string()
  File "/usr/lib/python3.6/email/message.py", line 158, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/lib/python3.6/email/generator.py", line 116, in flatten
    self._write(msg)
  File "/usr/lib/python3.6/email/generator.py", line 181, in _write
    self._dispatch(msg)
  File "/usr/lib/python3.6/email/generator.py", line 214, in _dispatch
    meth(msg)
  File "/usr/lib/python3.6/email/generator.py", line 272, in _handle_multipart
    g.flatten(part, unixfrom=False, linesep=self._NL)
  File "/usr/lib/python3.6/email/generator.py", line 116, in flatten
    self._write(msg)
  File "/usr/lib/python3.6/email/generator.py", line 181, in _write
    self._dispatch(msg)
  File "/usr/lib/python3.6/email/generator.py", line 214, in _dispatch
    meth(msg)
  File "/usr/lib/python3.6/email/generator.py", line 358, in _handle_message
    g.flatten(msg.get_payload(0), unixfrom=False, linesep=self._NL)
  File "/usr/lib/python3.6/email/message.py", line 253, in get_payload
    return self._payload[i]
IndexError: list index out of range

**Comment by gwasser** [comment]
Thank you for the example!
