### ISSUE TITLE
All tickets not showing

### ISSUE THREAD

**Issue by anorouzi** [django-helpdesk/django-helpdesk#800]
**Describe the bug**
I have installed the helpdesk inside Django 3.0 . and used rest api authentication in it. when assessing the helpdesk by (even super user or staff) the following error shown as alert.

DataTables warning: table id=ticketTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7

And the following inside the console:

GET /helpdesk/datatables_ticket_list/?draw=1&columns%5B0%5D%5Bdata%5D=id&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=ticket&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=priority&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=queue&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=status&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=created&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=due_date&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=assigned_to&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=true&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=submitter&columns%5B8%5D%5Bname%5D=&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=true&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B9%5D%5Bdata%5D=time_spent&columns%5B9%5D%5Bname%5D=&columns%5B9%5D%5Bsearchable%5D=true&columns%5B9%5D%5Borderable%5D=true&columns%5B9%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B9%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=25&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1580172920432 401 (Unauthorized)

**Expected behavior**
This should work but i don't know why this shown ?!
As it is Said 401 Unauthorized I have tried  and added the csrftoken token inside ticket_list.html but nothings happens. the following code used but without any chance it throw the alerts with the above error:
```
     var tasks_table = $('#ticketTable').DataTable({
         "language": {
             "emptyTable": "{% trans 'No Tickets Match Your Selection' %}"
         },
         "processing": true,
         "serverSide": true,
         "ajax": {
		         "url": "{% url 'helpdesk:datatables_ticket_list' urlsafe_query %}",
             "type": "GET",
			  "headers": {'X-CSRFToken': csrftoken},	
         },
```
Any advice on what should i do or where the errors is coming from ?

Thanks in Advance

**Comment by gwasser** [comment]
The "Unauthorized" error suggests to me that your web server is misconfigured. Are you using Apache or something else? Also just to confirm, are you using the latest `django-helpdesk` 0.2.x release?

**Comment by anorouzi** [comment]
I am using nginx with gunicorn.  And Also the latest django-helpdesk.
At first i have configured and used django rest api and also token and jwt authentication. It works properly. After adding helpdesk it throw errors on only on helpdesk All tickets. 
My thought was the using the api inside staff.py would prevent from accessing (just a  thought as it does not have permissions for rest api )at the following line :
```
@helpdesk_staff_member_required
@api_view(['GET'])
```
but with adding csrf token should works but don't know why this happens?

**Comment by anorouzi** [comment]
This is when correcting the authentication and it give the 500 internal server error :
```

Request Method: | GET
-- | --
https://mysite.com/helpdesk/datatables_ticket_list/?draw=1&columns%5B0%5D%5Bdata%5D=id&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=ticket&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=priority&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=queue&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=status&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=created&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=due_date&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=assigned_to&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=true&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=submitter&columns%5B8%5D%5Bname%5D=&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=true&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B9%5D%5Bdata%5D=time_spent&columns%5B9%5D%5Bname%5D=&columns%5B9%5D%5Bsearchable%5D=true&columns%5B9%5D%5Borderable%5D=true&columns%5B9%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B9%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=25&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1580178196083
3.0.1
JSONDecodeError
Expecting value: line 1 column 1 (char 0)
/usr/lib/python3.7/json/decoder.py in raw_decode, line 355
/home/mydesk/myappdir/myappenv/bin/python3
3.7.3
['/home/mydesk/myappdir',  '/home/mydesk/myappdir/myappenv/bin',  '/home/mydesk/myappdir/myappenv/lib/python37.zip',  '/home/mydesk/myappdir/myappenv/lib/python3.7',  '/home/mydesk/myappdir/myappenv/lib/python3.7/lib-dynload',  '/usr/lib/python3.7',  '/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages']
Tue, 28 Jan 2020 10:36:17 +0000

```

and below is the traceback from it:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)

During handling of the above exception (0), another exception occurred:
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mydesk/myappdir/myappenv/lib/python3.7/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/mydesk/myappdir/helpdesk/views/staff.py", line 980, in datatables_ticket_list
    query = Query(HelpdeskUser(request.user), base64query=query)
  File "/home/mydesk/myappdir/helpdesk/query.py", line 103, in __init__
    self.params = query_params if query_params else query_from_base64(base64query)
  File "/home/mydesk/myappdir/helpdesk/query.py", line 27, in query_from_base64
    query.update(json.loads(b64decode(b64data).decode('utf-8')))
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

Exception Type: JSONDecodeError at /helpdesk/datatables_ticket_list/
Exception Value: Expecting value: line 1 column 1 (char 0)
```

**Comment by anorouzi** [comment]
Solved it by Adding :
```
'rest_framework.authentication.BasicAuthentication',
'rest_framework.authentication.SessionAuthentication',
```
to DEFAULT_AUTHENTICATION_CLASSES in setting.py . If it doesn't set it throughs the above authentication error. 
 And solve the internal server error by getting the latest version again.
it becomes like this: 
```
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
	 'rest_framework.authentication.BasicAuthentication',
         'rest_framework.authentication.SessionAuthentication',
          (...)
     ),
    (...)
}
```
Maybe It should be added to documentations. 
Thanks Again

**Comment by RyanHope** [comment]
I am also experiencing this issue and the above mentioned fix does not work.

**Comment by RyanHope** [comment]
I have resolved the datatable/ajax warning that the OP described but I still dont have any tickets in my all tickets view. However, they show in the dashboard.

**Comment by RyanHope** [comment]
Ok solved my problem. It wasn't obvious from the demo app but when extending the base template block helpdesk_head and helpdesk_js are important ;)

**Comment by RyanHope** [comment]
Moved my website to a new server and now this error is back.... grr.

**Comment by RyanHope** [comment]
Fixed: issue was related to nginx + uwsgi... had to set buffer-size=65535 for my uwsgi config.

**Comment by uhurusurfa** [comment]
This works in the current setup.
If there is still an issue please raise another issue.
