### ISSUE TITLE
Make Demo is failing at 'demodesk migrate --noinput'

### ISSUE THREAD

**Issue by hxvxt2** [django-helpdesk/django-helpdesk#811]
Hey guys,

I'm new to Django and open source. Please bear with me if I'm missing something obvious.

**Describe the bug**
`Make Demo` is failing at `demodesk migrate --noinput`

**To Reproduce**
1.) `git clone https://github.com/django-helpdesk/django-helpdesk/`
2.) `pip install -r requirments.txt` 
4.) Tried trunning `make demo` but this gave me below error:-
```
pip3 install -e . --user
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
``` 
5.) So I removed the `--user` option from `Makefile`

`> vim makefile`
``` 
 78 #: demo - Setup demo project using Python3.
 79 .PHONY: demo
 80 demo:
 81         $(PIP) install -e . 
 82         $(PIP) install -e demo 
```
6.) Tried `make demo` once again. Got a new error on line # 83 of `makefile` i.e.  
 `demodesk migrate --noinput`

```
demodesk migrate --noinput
Traceback (most recent call last):
  File "/Users/vikrant.tyagi/.virtualenvs/djdesk-RzRsygL3/bin/demodesk", line 11, in <module>
    load_entry_point('django-helpdesk-demodesk', 'console_scripts', 'demodesk')()
  File "/Users/vikrant.tyagi/Documents/Lambda/djhelp/django-helpdesk/demo/demodesk/manage.py", line 22, in main
    execute_from_command_line(sys.argv)
  File "/Users/vikrant.tyagi/.virtualenvs/djdesk-RzRsygL3/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/vikrant.tyagi/.virtualenvs/djdesk-RzRsygL3/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/Users/vikrant.tyagi/.virtualenvs/djdesk-RzRsygL3/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/vikrant.tyagi/.virtualenvs/djdesk-RzRsygL3/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/vikrant.tyagi/.virtualenvs/djdesk-RzRsygL3/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/vikrant.tyagi/.virtualenvs/djdesk-RzRsygL3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/vikrant.tyagi/Documents/Lambda/djhelp/django-helpdesk/helpdesk/models.py", line 28, in <module>
    import pinax.teams.models
  File "/Users/vikrant.tyagi/.virtualenvs/djdesk-RzRsygL3/lib/python3.7/site-packages/pinax/teams/models.py", line 13, in <module>
    from pinax.invitations.models import JoinInvitation
  File "/Users/vikrant.tyagi/.virtualenvs/djdesk-RzRsygL3/lib/python3.7/site-packages/pinax/invitations/models.py", line 5, in <module>
    from account.models import SignupCode
  File "/Users/vikrant.tyagi/.virtualenvs/djdesk-RzRsygL3/lib/python3.7/site-packages/account/models.py", line 26, in <module>
    class Account(models.Model):
  File "/Users/vikrant.tyagi/.virtualenvs/djdesk-RzRsygL3/lib/python3.7/site-packages/django/db/models/base.py", line 111, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class account.models.Account doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
make: *** [demo] Error 1
```

**Comment by gwasser** [comment]
One suggestion is for you to download the latest release (0.2.x) rather than using the `master` branch. `master` has work toward the next version and may not be working right now. I see `pinax` in the error messages which was a recent addition.

You can install the latest release with:
`pip install django-helpdesk`
and then copy the demo folder to have a starting project.

**Comment by hxvxt2** [comment]
Thanks for the reply @gwasser 

>You can install the latest release with:
pip install django-helpdesk

I am using `pipenv` for virtual environment, so I ran `pip install django-helpdesk` as you suggested under my virtual environment. 

> and then copy the demo folder to have a starting project.

*(Sorry if this feels like I'm asking for spoonfeeding)* Copy the Demo folder from where? I hope you mean run a `git clone` and copy the Demo folder from there? Or was `pip install django-helpdesk` supposed to copy the package in my working directory? 

Why do I need to pip install django-helpdesk if I am still *git cloning* the repo? I think I'm getting confused with what you are suggesting and what [README.rst](https://github.com/django-helpdesk/django-helpdesk/tree/master/demo/demodesk) is suggesting.  

A little more help, please. Thanks for your time. 👍 

-Vikrant

**Comment by gwasser** [comment]
Pip gives you a good working install of Django helpdesk. It's not
guaranteed to work on master branch.

You can start a complete new Django project using the advice in the docs
and https://www.djangoproject.com/start/ (although use Django 2, doesn't
support 3 yet)

Or, you can git clone from a branch rather than master. So do:

`git clone -b 0.2.x`

To get the 0.2.x branch. If you do that, you can then try to run the demo
folder.

**Comment by hxvxt2** [comment]
Thanks again @gwasser 

It was the issue with the wrong branch. Switched to 0.2.x and it works like a charm. Thanks again! 

This looks like a prototype though. Do you know anyone who might be using this or some version of this for production? 

Thanks

**Comment by gwasser** [comment]
It's not a prototype, it's a long established software. Maybe not all the
bells and whistles but it works. Some folks have reported they use it in
production for small projects but I don't know how many.

**Comment by gwasser** [comment]
I'm going to close this since it seems the demo is working, but please file a new one if you have other questions.

**Comment by Mte90** [comment]
Downloading this repository and executing as the readme `make rundemo` I get that error:
```
Installing collected packages: django-helpdesk-demodesk
  Running setup.py develop for django-helpdesk-demodesk
Successfully installed django-helpdesk-demodesk
demodesk migrate --noinput
make: demodesk: File o directory non esistente
make: *** [Makefile:84: demo] Errore 127
```

Changing in the `Makefile` the `demodesk` command with `python /[path]/django-helpdesk/demo/demodesk/manage.py` fix the issue.
