### ISSUE TITLE
pip install failed with python 3.8 and django 3.0.5

### ISSUE THREAD

**Issue by renelabounek** [django-helpdesk/django-helpdesk#818]
**Describe the bug**
Based on your documentation, I have trid to install django-helpdesk in my virtual environment via "pip install django-helpdesk". But I have got error mesage listed below.

**To Reproduce**
(venv) [user@hostname projectfolder]$ pip install django-helpdesk
Collecting django-helpdesk
  Using cached django-helpdesk-0.2.21.tar.gz (3.3 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/user/codes/venv/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kz89aoc7/django-helpdesk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kz89aoc7/django-helpdesk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-kz89aoc7/django-helpdesk/pip-egg-info
         cwd: /tmp/pip-install-kz89aoc7/django-helpdesk/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/user/codes/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/home/user/codes/venv/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
        from setuptools import windows_support
      File "/home/user/codes/venv/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/usr/local/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(venv) [user@hostname projectfolder]$

**Expected behavior**
django-helpdesk will be installed at venv with python 3.8.2 and django 3.0.5.

**Desktop (please complete the following information):**
 - OS: CentOS 8
 - Version:
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

**Software version:**
Python 3.8.2
django-admin 3.0.5
pip 20.0.2

**Additional context**
In the projectfoldere, there are django project files like manage.py, etc. But I do not believe it is important for the current bug.

**Comment by renelabounek** [comment]
It was possibly error in python3.8 make install. I have reinstall/recompiled python3.8 and then the django-helpdesk installed succesfully.
