### ISSUE TITLE
Customer/User (non-staff non-superuser) unable to view or edit their submitted tickets

### ISSUE THREAD

**Issue by alligatorbait** [django-helpdesk/django-helpdesk#867]
**Describe the bug**
An authenticated user creates a ticket (who is not a superuser or staff) and is unable to view their own ticket.

**To Reproduce**
Django Settings:
SITE_ID = 1
HELPDESK_REDIRECT_TO_LOGIN_BY_DEFAULT = True
HELPDESK_ALLOW_NON_STAFF_TICKET_UPDATE = True
HELPDESK_KB_ENABLED = False
HELPDESK_VIEW_A_TICKET_PUBLIC = False
HELPDESK_SUBMIT_A_TICKET_PUBLIC = False
HELPDESK_MAX_EMAIL_ATTACHMENT_SIZE = 0
HELPDESK_DEFAULT_SETTINGS = {
        'use_email_as_submitter': False,
        'email_on_ticket_assign': True,
        'email_on_ticket_change': True,
        'login_view_ticketlist': True,
        'tickets_per_page': 25
        }

1. Authenticate user
2. Submit a ticket, validate email address populated field for email.
3. After submission redirected to /helpdesk/tickets/[ticket number] and page displaying 403 FORBIDDEN.
```
2020-08-25 18:31:24,922 WARNING log PID: 25421 ThreadID: 140086437427008 Forbidden (Permission denied): /helpdesk/tickets/6/
Traceback (most recent call last):
  File "lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "lib/python3.6/site-packages/helpdesk/decorators.py", line 45, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "lib/python3.6/site-packages/helpdesk/views/staff.py", line 287, in view_ticket
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
``` 

**Expected behavior**
Customer is able to view their own ticket after submission, as stated in 3. below from the Docs.
- User is directed to the /helpdesk/tickets/[ticket number] but should be directed to /helpdesk/view/... where they can view the ticket they entered.
- When loging into helpdesk the user starts on /helpdesk/tickets which displays all tickets and does not differentiate between their submitted tickets and others.
  - Dashboard is a better landing page, and if unprivileged the user should just be shown the section with tickets they submitted.
  - /helpdesk/view seems to be what the docs refer to, however this allows access to all tickets, to have some control I expected a user would only be able to view their submitted or owned tickets.
[Customer Facing Capabilities](https://django-helpdesk.readthedocs.io/en/master/index.html#customer-facing-capabilities)
Customers (who are not ‘staff’ users in Django) can:

1. Browse your knowledgebase / FAQ
2. Submit support requests via web/email
3. Review open and closed requests they submitted*

**Comment by alligatorbait** [comment]
I'm looking at this setting HELPDESK_ALLOW_NON_STAFF_TICKET_UPDATE = True and it appears that in decorators.py it allows the correct permissions for non-staff users to view pages. But then when user.py HelpdeskUser can_access_queue and can_access_ticket permissions do not check the HELPDESK_ALLOW_NON_STAFF_TICKET_UPDATE. This is in all code branches.
