### ISSUE TITLE
Unable to set up the Django project locally

### ISSUE THREAD

**Issue by hxvxt2** [django-helpdesk/django-helpdesk#875]
**Describe the bug**
Unable to set up the Django project locally

**To Reproduce**
1. Go to project documentation 'https://django-helpdesk.readthedocs.io/en/0.2.x/install.html'
2. `git clone git://github.com/django-helpdesk/django-helpdesk.git` 
3. Set `helpdesk` in `PYTHONPATH `
4. From the official documentation 
> If you’re on a brand new Django installation, make sure you do a migrate before adding `helpdesk` to your `INSTALLED_APPS`. This will avoid errors with trying to create User settings. 

So I commented out `helpdesk`:-
```python
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    'bootstrap4form',

    'account',  # Required by pinax-teams
    'pinax.invitations',  # required by pinax-teams
    'pinax.teams',  # team support
    # 'helpdesk',  # This is us!
    'reversion',  # required by pinax-teams
]
```
5. `❯ ./manage.py migrate helpdesk`
```shell
Traceback (most recent call last):
  File "./manage.py", line 25, in <module>
    main()
  File "./manage.py", line 22, in main
    execute_from_command_line(sys.argv)
  File "/Users/vikrant.tyagi/.virtualenvs/django-helpdesk-Io_sUKyi/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/vikrant.tyagi/.virtualenvs/django-helpdesk-Io_sUKyi/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/vikrant.tyagi/.virtualenvs/django-helpdesk-Io_sUKyi/lib/python3.7/site-packages/django/core/management/__init__.py", line 224, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/vikrant.tyagi/.virtualenvs/django-helpdesk-Io_sUKyi/lib/python3.7/site-packages/django/core/management/__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/vikrant.tyagi/.virtualenvs/django-helpdesk-Io_sUKyi/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 10, in <module>
    from django.core.management.sql import (
  File "/Users/vikrant.tyagi/.virtualenvs/django-helpdesk-Io_sUKyi/lib/python3.7/site-packages/django/core/management/sql.py", line 2, in <module>
    from django.db import models
  File "/Users/vikrant.tyagi/.virtualenvs/django-helpdesk-Io_sUKyi/lib/python3.7/site-packages/django/db/models/__init__.py", line 3, in <module>
    from django.db.models.aggregates import *  # NOQA
  File "/Users/vikrant.tyagi/.virtualenvs/django-helpdesk-Io_sUKyi/lib/python3.7/site-packages/django/db/models/aggregates.py", line 5, in <module>
    from django.db.models.expressions import Case, Func, Star, When
  File "/Users/vikrant.tyagi/.virtualenvs/django-helpdesk-Io_sUKyi/lib/python3.7/site-packages/django/db/models/expressions.py", line 8, in <module>
    from django.db.models import fields
  File "/Users/vikrant.tyagi/.virtualenvs/django-helpdesk-Io_sUKyi/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 11, in <module>
    from django import forms
  File "/Users/vikrant.tyagi/.virtualenvs/django-helpdesk-Io_sUKyi/lib/python3.7/site-packages/django/forms/__init__.py", line 6, in <module>
    from django.forms.boundfield import *  # NOQA
  File "/Users/vikrant.tyagi/.virtualenvs/django-helpdesk-Io_sUKyi/lib/python3.7/site-packages/django/forms/boundfield.py", line 3, in <module>
    from django.forms.utils import flatatt, pretty_name
  File "/Users/vikrant.tyagi/.virtualenvs/django-helpdesk-Io_sUKyi/lib/python3.7/site-packages/django/forms/utils.py", line 7, in <module>
    from django.utils.html import escape, format_html, format_html_join, html_safe
  File "/Users/vikrant.tyagi/.virtualenvs/django-helpdesk-Io_sUKyi/lib/python3.7/site-packages/django/utils/html.py", line 11, in <module>
    from django.utils.http import RFC3986_GENDELIMS, RFC3986_SUBDELIMS
  File "/Users/vikrant.tyagi/.virtualenvs/django-helpdesk-Io_sUKyi/lib/python3.7/site-packages/django/utils/http.py", line 8, in <module>
    from email.utils import formatdate
  File "/Users/vikrant.tyagi/Documents/Lambda/wander/django-helpdesk/helpdesk/email.py", line 11, in <module>
    from django.db.models import Q
ImportError: cannot import name 'Q' from 'django.db.models' (/Users/vikrant.tyagi/.virtualenvs/django-helpdesk-Io_sUKyi/lib/python3.7/site-packages/django/db/models/__init__.py)
```

**Expected behavior**
Should have migrated the models

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.4 (19E287)
 - Browser: Chrome
 - Version 85.0.4183.121 (Official Build) (64-bit)Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by danialbagheri** [comment]
Hi, 

I am not familiar with this project in particular, but this doesn't sound like an issue, it seems that you have not setup a `virtualenv` first, you would then need to install the packages in `requirements.txt` file. The error you have indicates that it cannot import a module from django, meaning django is not installed. 

Let me know if you have any question.

**Comment by gwasser** [comment]
Yes I agree, please check that django is installed and that you follow all the necessary django installation instructions including setting up a database *first* before attempting to install django-helpdesk. See: https://docs.djangoproject.com/en/2.2/intro/install/.

**Comment by gwasser** [comment]
I'm going to close this comment for now to clean up our bug reports but let us know if you have any follow up questions.
