### ISSUE TITLE
Error 500 on Demo App

### ISSUE THREAD

**Issue by Benbb96** [django-helpdesk/django-helpdesk#922]
I was just testing the demo app while I came accross a ticket which produce an error when trying to access the detail page : http://django-helpdesk-demo.herokuapp.com/tickets/10400/

I wanted to know what the error was to reproduce it and try to fix it.

**Comment by gwasser** [comment]
I've encountered a number of tickets that create a 500 error for some
reason. Let me see if I can grab the log and share.

**Comment by gwasser** [comment]
I think the issue is that these tickets don't have a submitter email for
some reason. Is it possible to remove a submitter email from the ticket via
the email cc screen?

**Comment by Benbb96** [comment]
No, I don't think it's possible to remove the submitter email from the cc screen. But it's possible to create a ticket without specifying the submitter email. The Demo user seems to be staff, so the submitter email field is optional for him.

However, I've tried to reproduce it in my environment and a ticket without a submitter email doesn't raise a 500 error.

Did you find anything else in the logs which could give a hint ?

**Comment by gwasser** [comment]
I removed a bunch of tickets to keep the heroku database within hobby limits so accidentally removed the ticket you originally referenced. But here's the log for a similar one that causes a 500 error:

2021-01-07T00:58:52.907942+00:00 app[web.1]: Internal Server Error: /tickets/12147/
2021-01-07T00:58:52.907943+00:00 app[web.1]: Traceback (most recent call last):
2021-01-07T00:58:52.907943+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/urls/base.py", line 72, in reverse
2021-01-07T00:58:52.907944+00:00 app[web.1]: extra, resolver = resolver.namespace_dict[ns]
2021-01-07T00:58:52.907944+00:00 app[web.1]: KeyError: 'admin'
2021-01-07T00:58:52.907945+00:00 app[web.1]: 
2021-01-07T00:58:52.907945+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2021-01-07T00:58:52.907946+00:00 app[web.1]: 
2021-01-07T00:58:52.907946+00:00 app[web.1]: Traceback (most recent call last):
2021-01-07T00:58:52.907946+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
2021-01-07T00:58:52.907947+00:00 app[web.1]: response = get_response(request)
2021-01-07T00:58:52.907947+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
2021-01-07T00:58:52.907948+00:00 app[web.1]: response = wrapped_callback(request, *callback_args, **callback_kwargs)
2021-01-07T00:58:52.907948+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
2021-01-07T00:58:52.907948+00:00 app[web.1]: return view_func(request, *args, **kwargs)
2021-01-07T00:58:52.907949+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/helpdesk/views/staff.py", line 379, in view_ticket
2021-01-07T00:58:52.907949+00:00 app[web.1]: submitter_userprofile_url = reverse(
2021-01-07T00:58:52.907949+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/urls/base.py", line 83, in reverse
2021-01-07T00:58:52.907950+00:00 app[web.1]: raise NoReverseMatch("%s is not a registered namespace" % key)
2021-01-07T00:58:52.907950+00:00 app[web.1]: django.urls.exceptions.NoReverseMatch: 'admin' is not a registered namespace

**Comment by Benbb96** [comment]
Hum, I think the admin module is not linked into the demo app.

Can you check that line is in `urls.py` : 

    url(r'^admin/', admin.site.urls),

**Comment by gwasser** [comment]
Ah you're right that was missing. I left a note to myself I removed admin
as a quick and dirty way of trying to prevent someone from changing the
demo user password. Do you know a better way to do that? maybe I need to
include a custom user template that removes the change password option.

**Comment by Benbb96** [comment]
I believe the best way is to make him non staff (but I think it's already the case), thus he won't be able to log in the admin and change his password.

**Comment by gwasser** [comment]
Thanks! Yeah maybe I'm overcomplicating this haha. Looks like just a demo
config error though and not a bug in django-helpdesk, so that has me
feeling better about the 0.3.0 beta.

**Comment by gwasser** [comment]
I think it's all fine, I updated the demo the 0.3.0 release, so I'm going to close this. Thanks!
